name: CI - FastAPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: 🧹 Run linter (flake8)
        run: flake8 app/ tests/

      - name: 🛡️ Run security checks with Bandit
        run: bandit -r app/

      - name: 🔒 Check vulnerable dependencies with pip-audit
        run: pip-audit

      - name: 🧪 Run tests
        run: pytest --cov=app tests/

      - name: 📊 Upload coverage report (text summary)
        run: coverage report