name: CI - FastAPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flake8-linter:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: 🧹 Run linter (flake8)
        run: flake8 app/ tests/
        continue-on-error: true

  bandit-security:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 🛡️ Run security checks with Bandit
        run: bandit -r app/
        continue-on-error: true

  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 🔒 Check vulnerable dependencies with pip-audit
        run: pip-audit
        continue-on-error: true

  tests-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: 🧪 Run tests
        run: PYTHONPATH=. pytest --cov=app --cov-fail-under=80 tests/
        continue-on-error: true
      - name: 📊 Upload coverage report (text summary)
        run: coverage report
        continue-on-error: true

  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
      - name: 🔍 Scan for secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .github/gitleaks.toml
        continue-on-error: true
